services:
    - type: web
      name: skate-lab-demo
      env: php  # Garante que o ambiente seja PHP
      
      plan: free 
      repo: https://github.com/ferreiravih/Skate-Lab # Confirme seu repositório
      branch: main 
      rootDir: . 
      
      # render-php (que é baseado no Heroku Buildpack)
      envVars:
        - key: WEB_SERVER
          value: apache2 # Define explicitamente o servidor web como Apache
        
        - key: SUPABASE_DATABASE_URL
          sync: false
      
      # Estes comandos permanecem, mas agora o 'composer' estará disponível
      buildCommand: 'composer install --no-dev'
      startCommand: 'vendor/bin/heroku-php-apache2'
      
      healthCheckPath: /